In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import pywt
import os
import tqdm 
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_squared_error, r2_score
import seaborn as sns
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [160]:
def fix_file(df):
    df = pd.Series(df[df.columns[0]])
    #데이터 형식이 안맞는 경우 
    fixed = pd.DataFrame()
    fixed['H'] = df.str.split(';').str[0]
    fixed['M'] = df.str.split(';').str[1]
    fixed['S'] = df.str.split(';').str[2]
    fixed['MS'] = df.str.split(';').str[3]
    fixed['Horiz'] = df.str.split(';').str[4]
    fixed['Vert'] = df.str.split(';').str[5]
    return fixed


def read_data(path):
    file_list = os.listdir(path)
    total_list = []
    for i in range(len(file_list)):
        tem = pd.read_csv(path+file_list[i])
        if len(tem.columns) == 6:
            tem.columns = ['H','M','S','MS','Horiz','Vert']
            total_list.append(tem)
            
        if len(tem.columns) == 1:
            tem2 = fix_file(tem)
            tem2.columns = ['H','M','S','MS','Horiz','Vert']
            total_list.append(tem2)
            
        else:
            continue
            #tem.columns = ['H','M','S','MS','Horiz','Vert']
        #usecols =['hour','min','second','0.x','Horiz','Vert']
        
    merged_data = pd.concat([i for i in total_list],axis = 0)

    return merged_data 

## Target PATH
path = "./Learning_set/"
files = os.listdir(path)
files


for get_file in files:
    path2 = path+get_file+"/"
    
    tem = read_data(path2)
    tem.to_csv('./pro_learning_raw/'+ get_file+".csv",index= False)

In [30]:
merged_data = pd.concat([i for i in total],axis = 0)
merged_data

      hour  min  second       0.x  Horiz   Vert
0        8   33       1  378200.0 -0.025  0.432
1        8   33       1  378240.0 -0.104  0.008
2        8   33       1  378280.0  0.056 -0.264
3        8   33       1  378320.0  0.074 -0.195
4        8   33       1  378360.0 -0.147 -0.373
...    ...  ...     ...       ...    ...    ...
2554    13   33      11  477970.0 -0.566  0.255
2555    13   33      11  478010.0 -0.528  0.779
2556    13   33      11  478050.0 -0.732  0.532
2557    13   33      11  478080.0 -0.284 -0.130
2558    13   33      11  478120.0 -0.607  0.797

[4611318 rows x 6 columns]